- src/components/Board.js
- src/components/History.js
- src/components/PrimaryButtons.js
- src/index.css
Fix issue https://github.com/programarivm/redux-chess/issues/12
> Add mobile responsivity

- package.json
- src/components/Board.js
- src/components/Timer.js
- src/index.css
At this moment a basic timer is being displayed, however it should also be synced.
> Displayed one timer only

- src/components/ButtonsPlayFriendMode.js
- src/components/Chess.js
Added a button to propose a takeback as per guidelines
> Add a button to propose a takeback #132

- src/components/ButtonsResignGame.js
- src/components/Chess.js
Add a button to resign the game
> Add a button to resign the game #123

- src/components/ButtonsPlayFriendMode.js
Added a button to offer a draw, no backend functionality is added yet
> Add a button to offer a draw #124

- src/components/Board.js
Issue: #133 
I implemented the methods onDrag, onDrop and onDragOver, to handle mouse events.
> Implements drag-and-drop functionality

- src/actions/serverActions.js
- src/components/Buttons.js
- src/components/Chess.js
- src/components/GetFenDialog.js
- src/constants/getFenDialogActionTypes.js
- src/listeners/wsMssgListener.js
- src/reducers/getFenDialogReducer.js
- src/reducers/rootReducer.js
Added a new option to display the FEN string
This PR is regarding issue #139
> Add a new option to display the FEN string

- src/components/Buttons.js
Closes https://github.com/chesslablab/redux-chess/issues/196
> Added the PGN Movetext option to the Settings menu

- src/components/Buttons.js
Closes https://github.com/chesslablab/redux-chess/issues/191
> Added the Load PGN button

- src/components/Buttons.js
Closes https://github.com/chesslablab/redux-chess/issues/193
> Added the 'Play With the Computer' button

- src/components/CreateInviteCodeDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/189
> Allowed selecting an increment in seconds

- src/components/AlgebraicNotationFiles.js
- src/components/AlgebraicNotationRanks.js
- src/components/Board.js
- src/index.css
Closes https://github.com/chesslablab/redux-chess/issues/176
> Added algebraic notation files and ranks

- src/index.css
Closes https://github.com/chesslablab/redux-chess/issues/179
> Fixed CSS for the board to be displayed on Firefox

- src/components/Buttons.js
Closes https://github.com/chesslablab/redux-chess/issues/212
> Merged the Load buttons into one

- src/components/Buttons.js
- src/components/Chess.js
- src/components/PgnDialog.js
- src/constants/pgnDialogActionTypes.js
- src/reducers/pgnDialogReducer.js
- src/reducers/rootReducer.js
Closes https://github.com/chesslablab/redux-chess/issues/197
> Displayed the PGN dialog

- src/components/Buttons.js
- src/components/Chess.js
- src/components/LoadPgnDialog.js
- src/constants/loadPgnDialogActionTypes.js
- src/reducers/loadPgnDialogReducer.js
- src/reducers/rootReducer.js
Closes https://github.com/chesslablab/redux-chess/issues/195
> Displayed the 'Load PGN' dialog

- src/components/Dialog/PgnDialog.js
- src/constants/pgnDialogActionTypes.js
- src/reducers/pgnDialogReducer.js
Closes https://github.com/chesslablab/redux-chess/issues/198
> Cleaned up the PGN Movetext dialog

- src/components/Dialog/PgnDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/202
> Wrote PGN movetext into the clipboard

- src/components/MainBreadcrumbs.js
Closes https://github.com/chesslablab/redux-chess/issues/231
> Displayed option name

- package.json
- src/components/Buttons.js
- src/components/Chess.js
- src/components/Dialog/CreateInviteCodeDialog.js
- src/components/Dialog/DrawAcceptDialog.js
- src/components/Dialog/DrawOfferDialog.js
- src/components/Dialog/EnterInviteCodeDialog.js
- src/components/Dialog/FenDialog.js
- src/components/Dialog/HeuristicPictureDialog.js
- src/components/Dialog/LoadFenDialog.js
- src/components/Dialog/LoadPgnDialog.js
- src/components/Dialog/PgnDialog.js
- src/components/Dialog/PlayLikeGrandmasterDialog.js
- src/components/Dialog/RematchAcceptDialog.js
- src/components/Dialog/RematchOfferDialog.js
- src/components/Dialog/ResignAcceptDialog.js
- src/components/Dialog/TakebackAcceptDialog.js
- src/components/Dialog/TakebackOfferDialog.js
- src/components/GameClock/BlackTimer.js
- src/components/GameClock/WhiteTimer.js
- src/components/HeuristicPicture.js
- src/components/History.js
- src/components/InfoAlert.js
- src/components/MainBreadcrumbs.js
- src/components/MoveValidator.js
- src/components/PlayFriendMode/Buttons.js
- src/components/PlayFriendMode/GameButtons.js
- src/components/PlayFriendMode/GameOverButtons.js
Closes https://github.com/chesslablab/redux-chess/issues/236
> Issue/236 update to m UI 5

- src/components/Buttons.js
Closes https://github.com/chesslablab/redux-chess/issues/243
> changed Play with the computer button to Training

- src/components/InfoAlert.js
- src/listeners/wsMssgListener.js
Closes https://github.com/chesslablab/redux-chess/issues/249
> Fetched and displayed the chess openings

- src/actions/serverActions.js
- src/listeners/wsMssgListener.js
Closes https://github.com/chesslablab/redux-chess/issues/242
> Snake cased the command names

- src/components/Dialog/OpeningSearchEcoDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/247
> Added a default option

- src/components/AjaxLoader/ChessOpeningSearchEcoAjaxLoader.js
- src/components/Dialog/OpeningSearchEcoDialog.js
- src/constants/ajaxLoader/chessOpeningSearchEcoAjaxLoaderActionTypes.js
- src/reducers/chessOpeningSearchEcoAjaxLoaderReducer.js
- src/reducers/rootReducer.js
Closes https://github.com/chesslablab/redux-chess/issues/255
> Implemented Redux flow

- src/components/Dialog/ChessOpeningSearchNameDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/259
> Reset the openings after loading the selected movetext

- README.md
- src/actions/serverActions.js
- src/components/Buttons.js
- src/components/Chess.js
- src/components/Dialog/ChessOpeningSearchEcoDialog.js
- src/components/Dialog/ChessOpeningSearchMovetextDialog.js
- src/components/Dialog/ChessOpeningSearchNameDialog.js
- src/listeners/wsMssgListener.js
Closes https://github.com/chesslablab/redux-chess/issues/281
> Dehardcoded the API parameters

- src/components/Dialog/HeuristicPictureDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/287
> Added button

- package.json
- src/components/Dialog/HeuristicPictureDialog.js
- src/components/HeuristicPicture.js
Closes https://github.com/chesslablab/redux-chess/issues/288
> Installed html2canvas and implemented the handleDownloadImage() function

- src/components/Dialog/CreateInviteCodeDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/306
> Refactored the CreateInviteCodeDialog component

- src/components/Dialog/ChessOpeningSearchMovetextDialog.js
- src/components/Dialog/ChessOpeningSearchNameDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/248
> Displayed info alert

- src/features/dialog/CheckmateSkillsDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/322
> Added the 'King and queen vs. king' option

- src/features/playMode/StartedButtonsPlayMode.js
Closes https://github.com/chesslablab/redux-chess/issues/319
> Disabled the 'Propose a Takeback' button if no movetext is found

- src/features/dialog/PlayComputerDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/328
> Refactored PlayComputerDialog

- src/features/dialog/CheckmateSkillsDialog.js
- src/ws/WsAction.js
Closes https://github.com/chesslablab/redux-chess/issues/329
> Added a new random checkmate type

- package.json
- src/__tests__/components/Chess.test.js
> Fix rook position tests

- package.json
- src/__tests__/components/Chess.test.js
> Add PGN dialog test

- src/features/table/PlayOnlineTable.js
Closes https://github.com/chesslablab/redux-chess/issues/352
> Displayed image

- src/features/board/Capablanca80Board.js
- src/features/board/Chess960Board.js
- src/features/board/ClassicalBoard.js
- src/features/board/Squares.js
Closes https://github.com/chesslablab/redux-chess/issues/362
> Implemented filterMove()

- src/features/board/boardSlice.js
Closes https://github.com/chesslablab/redux-chess/issues/364
> Fixed error

- src/features/SecondaryButtons.js
- src/features/mode/modeSlice.js
- src/ws/WsEvent.js
Closes https://github.com/chesslablab/redux-chess/issues/366
> Refactored modeSlice

- src/features/dialog/LoadFenDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/350
> Allowed to select a variant

- src/features/dialog/LoadFenDialog.js
- src/ws/WsAction.js
- src/ws/WsEvent.js
Closes https://github.com/chesslablab/redux-chess/issues/369
> Updated LoadFenDialog

- src/features/ws/WsEvent.js
- src/features/ws/WsEventListener.js
Closes https://github.com/chesslablab/redux-chess/issues/381
> Implemented WsEvent.onError()

- src/features/SecondaryButtons.js
Closes https://github.com/chesslablab/redux-chess/issues/383
> Sent FEN string to the API endpoint

- src/features/dialog/SearchGamesDialog.js
Closes https://github.com/chesslablab/redux-chess/issues/387
> Search by movetext

- src/features/ws/WsEvent.js
Closes https://github.com/chesslablab/react-chess/issues/386
> Hid the progress bar

- src/features/board/Squares.js
Displaying the positions from a to h like this
> add: position a - h

- src/features/board/Squares.js
- src/index.css
right click to toggle the red highlight
> add: right click to toggle highlight

- src/features/MainButtons.js
- src/features/dialog/CreateInviteCodeDialog.js
Closes https://github.com/chesslablab/react-chess/issues/407
> Reset the play mode

- src/features/mode/analysis/StartedButtonsAnalysisMode.js
- src/features/mode/fen/StartedButtonsFenMode.js
- src/features/mode/gm/StartedButtonsGmMode.js
- src/features/mode/pgn/StartedButtonsPgnMode.js
- src/features/mode/stockfish/StartedButtonsStockfishMode.js
Closes https://github.com/chesslablab/react-chess/issues/395
> Undo Move button on the current position

- src/common/Animation.js
- src/features/MainButtons.js
- src/features/board/Squares.js
- src/features/board/boardSlice.js
- src/features/mode/play/FinishedButtonsPlayMode.js
- src/features/mode/play/StartedButtonsPlayMode.js
- src/features/timer/BlackTimer.js
- src/features/timer/WhiteTimer.js
- src/features/ws/WsEvent.js
Closes https://github.com/chesslablab/react-chess/issues/406
> Fixed stalemate

- tests/ChesslaBlab.side
Closes https://github.com/chesslablab/react-chess/issues/398
> Added test

- src/features/mode/play/StartedButtonsPlayMode.js
Closes https://github.com/chesslablab/react-chess/issues/419
> Refactored StartedButtonsPlayMode

- src/features/mode/play/StartedButtonsPlayMode.js
Closes https://github.com/chesslablab/react-chess/issues/420
> Displayed info message

- package.json
- src/features/nav/Nav.js
- src/features/nav/navConst.js
- src/features/ws/WsEvent.js
- src/features/ws/WsEventListener.js
Closes https://github.com/chesslablab/react-chess/issues/432
> Correspondence

- package.json
- src/features/nav/Nav.js
Issue #432 
Closes #432
DISCRIPTION
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
TYPE OF CHANGE
replace in media query  (min-width:900px)  to    (min-width:1100px)
> Fix:Correpondence and its icon out off there box in chesslaBlab website #432

- package.json
- src/features/nav/Nav.js
- src/features/nav/navConst.js
ssue https://github.com/chesslablab/react-chess/issues/432
Closes https://github.com/chesslablab/react-chess/issues/432
DISCRIPTION
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
TYPE OF CHANGE
let's rename the Correspondence button as Inbox in the [src/features/nav/Nav.js](https://github.com/chesslablab/react-chess/blob/master/src/features/nav/Nav.js) component.
> Fix:Correpondence and its icon out off there box in chesslaBlab website #432 

- src/features/nav/dialog/CreateInboxCodeDialog.js
> feat: removed informative message from the create inbox dialog box

- src/features/panel/fen/StartedButtons.js
- src/features/panel/san/StartedButtons.js
- src/features/panel/stockfish/StartedButtons.js
Hello @programarivm, please check it and merge this PR. 
Closes #437
> Fix:Rename the text of the buttons

- src/features/mode/san/dialog/LoadSanDialog.js
Closes https://github.com/chesslablab/react-chess/issues/445
> Updated LoadSanDialog

- src/features/panel/rav/RavTable.js
Closes https://github.com/chesslablab/react-chess/issues/449
> Improved the usability of the RAV reader

- src/features/nav/dialog/CreateInboxCodeDialog.js
Closes https://github.com/chesslablab/react-chess/issues/447
> Conditionally created the settings object

- src/common/Movetext.js
Closes https://github.com/chesslablab/react-chess/issues/455
> Removed ellipsis

- src/common/Movetext.js
- src/features/panel/rav/RavTable.js
Closes https://github.com/chesslablab/react-chess/issues/452
> Implemented Movetext.description()

- src/features/mode/play/dialog/CreateInviteCodeDialog.js
Closes https://github.com/chesslablab/react-chess/issues/448
> Neeravbhaskarla

- README.md
Update README.md with formatting changes and license link
PS: Sorry about the Pull Request branch name, I will make sure to try and rename it in the future.
> Update README.md with formatting changes and license link

- src/features/HeuristicsBar.js
Closes #479 
Removed unnecessary constants from `HeuristicsBar.js` and optimized code.
> Remove unnecessary constants from the HeuristicsBar component

- src/features/board/CapablancaBoard.js
Closes https://github.com/chesslablab/react-chess/issues/488
> Removed constants

- src/features/panel/Buttons.js
Closes https://github.com/chesslablab/react-chess/issues/482
> Used the spread operator

- src/features/panel/Buttons.js
- src/features/ws/Ws.js
- src/features/ws/WsEvent.js
- src/features/ws/WsEventListener.js
Closes https://github.com/chesslablab/react-chess/issues/507
> Implemented handleHeuristics()

- src/features/panel/Buttons.js
Closes https://github.com/chesslablab/react-chess/issues/509
> Updated the call to the /api/heuristics endpoint

- src/features/mode/san/dialog/SearchMovetextDialog.js
Closes https://github.com/chesslablab/react-chess/issues/498
> Fixed the movetext search

- src/features/nav/Nav.js
Closes https://github.com/chesslablab/react-chess/issues/546
> Issue #546 : Made the hamburger menu for mobile screen

- src/features/nav/AnalysisBoard.js
- src/features/nav/Nav.js
Closes https://github.com/chesslablab/react-chess/issues/551
> Implemented AnalysisBoard

- src/features/nav/Nav.js
- src/features/nav/Play.js
Closes https://github.com/chesslablab/react-chess/issues/552
> Implemented Play

- src/features/nav/Nav.js
- src/features/nav/OpeningSearch.js
> Created OpeningSearch subcomponent

- src/features/nav/Database.js
- src/features/nav/Nav.js
- src/features/nav/OpeningSearch.js
Closes #554, also fixed a typo of the anchor in OpeningSearch subcomponent
> Created Database subcomponent

- src/features/nav/Nav.js
- src/features/nav/Training.js
> Created Training subcomponent

- src/features/panel/MovesTable.js
Closes https://github.com/chesslablab/react-chess/issues/568
> Fixed MovesTable

- src/features/mode/rav/table/AnnotatedGamesTable.js
Closes https://github.com/chesslablab/react-chess/issues/571
> Added Round

- src/features/panel/GameMetadataTable.js
Closes https://github.com/chesslablab/react-chess/issues/572
> Updated GameMetadataTable

- src/App.js
- src/app/rootReducer.js
- src/features/mode/ImageUploadSlice.js
- src/features/mode/upload/dialog/UploadImageDialog.js
- src/features/nav/AnalysisBoardMenu.js
> Analysis board menu update

- src/features/board/BoardSlider.js
- src/features/board/ResizeSlider.js
- src/features/board/VariantBoard.js
- src/index.css
Closes https://github.com/chesslablab/react-chess/issues/584
> 584 add a mui slider to allow changing the chessboard size

- src/features/board/BoardSlider.js
- src/features/board/VariantBoard.js
- src/index.css
> Slider added for changing chessboard size

- src/features/mode/fen/dialog/LoadImageDialog.js
> Added input file functionality

- tests/mocha/playc50.spec.js
> Refactor: Transistion playC50 test to Mocha

- tests/mocha/playa73.spec.js
> test: add a73 test

- package.json
Closes https://github.com/chesslablab/react-chess/issues/592
> npm install --save selenium-webdriver

- src/features/board/boardSlice.js
Closes https://github.com/chesslablab/react-chess/issues/678
> Removed optional chaining

- src/features/panel/Buttons.js
Closes https://github.com/chesslablab/react-chess/issues/699
> Add a new game action called Explain Position

- .env.example
- README.md
- public/index.html
- src/__tests__/ChesslaBlab.side
- src/__tests__/automated/en_passant_capture_and_promote.spec.js
- src/__tests__/automated/play_a73.spec.js
- src/__tests__/automated/play_c50.spec.js
Closes https://github.com/chesslablab/react-chess/issues/704
> Renamed reactchess.net as ui.chesslablab.net

- .env.example
- README.md
- public/index.html
- src/__tests__/ChesslaBlab.side
- src/__tests__/automated/en_passant_capture_and_promote.spec.js
- src/__tests__/automated/play_a73.spec.js
- src/__tests__/automated/play_c50.spec.js
Closes https://github.com/chesslablab/react-chess/issues/709
> Renamed ui.chesslablab.net as ui.chesslablab.org

- src/features/alert/WarningAlert.js
- src/features/board/Board.js
- src/features/board/BoardAudio.js
- src/features/nav/Nav.js
- src/features/nav/dialog/CreateInboxCodeDialog.js
- src/features/nav/dialog/EnterInboxCodeDialog.js
- src/features/nav/dialog/EventsStatsDialog.js
- src/features/nav/dialog/HelpDialog.js
- src/features/nav/dialog/OpeningsStatsDialog.js
- src/features/nav/dialog/PlayersStatsDialog.js
- src/features/nav/dialog/SettingsDialog.js
Closes https://github.com/chesslablab/react-chess/issues/712
> Added 'use client'

- src/features/mode/san/table/SearchGamesTable.js
> Removed overriding of default color
